#pragma once
// =============================================================================
// bfv_params.cuh — Shared types and constants for BFV Layer 1 CUDA kernels
//
// No dependency on Phantom-FHE, SEAL, or any other FHE library.
// =============================================================================

#include <cstdint>
#include <cstddef>

namespace bfv_core {

// ---------------------------------------------------------------------------
// Compile-time limits
// ---------------------------------------------------------------------------
static constexpr int MAX_RNS_PRIMES = 8;   // max primes in base Q or special P
static constexpr int MAX_POLY_DEG   = 32768;

// ---------------------------------------------------------------------------
// NTT-friendly 60-bit primes for N = 32768 (2^16 | p - 1).
//
// Generated by: find p ≡ 1 (mod 65536), p prime, 2^59 < p < 2^60.
// Verified with sympy. Primitive 2^16-th roots computed below.
// Use the first L of these for the RNS base Q, and the next K for special P.
// ---------------------------------------------------------------------------
static constexpr uint64_t DEFAULT_PRIMES[8] = {
    0xffffffffffc0001ULL,   // 1152921504606584833  prim_root=10
    0xfffffffff840001ULL,   // 1152921504598720513  prim_root=5
    0xfffffffff6a0001ULL,   // 1152921504597016577  prim_root=3
    0xfffffffff5a0001ULL,   // 1152921504595968001  prim_root=13
    0xfffffffff550001ULL,   // 1152921504595640321  prim_root=3
    0xfffffffff330001ULL,   // 1152921504593412097  prim_root=5
    0xfffffffff2a0001ULL,   // 1152921504592822273  prim_root=5
    0xfffffffff240001ULL,   // 1152921504592429057  prim_root=5
};

// Corresponding primitive 2N-th roots of unity (for N = MAX_POLY_DEG = 32768):
// g_prim[i] = primitive_root(DEFAULT_PRIMES[i]) ^ ((p-1)/(2N)) mod p
static constexpr uint64_t DEFAULT_PRIM_ROOTS_2N[8] = {
    683635763366557341ULL,
    684110995036099206ULL,
    741224627014235163ULL,
    965330802377619326ULL,
    327243900421176358ULL,
    618459889430362704ULL,
    200747066506169951ULL,
    1013038448189332084ULL,
};

// ---------------------------------------------------------------------------
// NttTable: precomputed per-prime NTT tables (device memory)
// ---------------------------------------------------------------------------
struct NttTable {
    uint64_t p;          // prime
    uint64_t g;          // primitive 2N-th root of unity mod p
    uint64_t g_inv;      // g^{-1} mod p (primitive inverse root)
    uint64_t N_inv;      // N^{-1} mod p (for INTT normalization)
    int      N;          // polynomial degree this table is for
    // Device arrays, each of size N:
    uint64_t* roots;     // roots[i] = g^i mod p, bit-reversed order
    uint64_t* roots_inv; // roots_inv[i] = g_inv^i mod p, bit-reversed order
};

// ---------------------------------------------------------------------------
// RnsContext: everything needed to do arithmetic on a single RNS-level poly
// ---------------------------------------------------------------------------
struct RnsContext {
    int        N;                       // polynomial degree
    int        L;                       // number of base primes (Q)
    int        K;                       // number of special primes (P)
    NttTable   base_tables[MAX_RNS_PRIMES];  // for Q primes [0..L-1]
    NttTable   spc_tables[MAX_RNS_PRIMES];   // for P primes [0..K-1]
    // Precomputed ModUp/ModDown constants (see rns.cuh)
    // base->special conversion
    uint64_t*  modup_factors;  // device: [L * K] matrix — (Q/q_i)^{-1}_{q_i} * (Q/q_i mod p_j)
    // special->base for ModDown
    uint64_t*  moddown_P_inv_Q; // device: [L] array — P^{-1} mod q_i  (single-prime P case)
    uint64_t   P;               // product of special primes (only meaningful if K=1 or small)
};

// ---------------------------------------------------------------------------
// Device utility: modular reduction
// ---------------------------------------------------------------------------

// Modular addition: (a + b) mod p, where a, b < p
__device__ __host__ __forceinline__
uint64_t addmod(uint64_t a, uint64_t b, uint64_t p) {
    uint64_t r = a + b;
    return (r >= p) ? r - p : r;
}

// Modular subtraction: (a - b) mod p, where a, b < p
__device__ __host__ __forceinline__
uint64_t submod(uint64_t a, uint64_t b, uint64_t p) {
    return (a >= b) ? a - b : a + p - b;
}

// Modular multiplication: (a * b) mod p, where a, b < p < 2^62
// Uses __uint128_t for the product — available on all CUDA 64-bit targets.
__device__ __host__ __forceinline__
uint64_t mulmod(uint64_t a, uint64_t b, uint64_t p) {
    return (uint64_t)((__uint128_t)a * b % p);
}

// Modular negation: (-a) mod p
__device__ __host__ __forceinline__
uint64_t negmod(uint64_t a, uint64_t p) {
    return (a == 0) ? 0 : (p - a);
}

// Modular exponentiation: base^exp mod p (host-side, for table init)
__host__ inline
uint64_t powmod(uint64_t base, uint64_t exp, uint64_t p) {
    uint64_t result = 1;
    base %= p;
    while (exp > 0) {
        if (exp & 1) result = (uint64_t)((__uint128_t)result * base % p);
        base = (uint64_t)((__uint128_t)base * base % p);
        exp >>= 1;
    }
    return result;
}

// Modular inverse: a^{-1} mod p (host, requires p prime — Fermat)
__host__ inline
uint64_t invmod(uint64_t a, uint64_t p) {
    return powmod(a, p - 2, p);
}

// Bit-reverse integer of `bits` bits
__host__ __device__ __forceinline__
uint32_t bit_reverse(uint32_t x, int bits) {
    uint32_t r = 0;
    for (int i = 0; i < bits; i++) {
        r = (r << 1) | (x & 1);
        x >>= 1;
    }
    return r;
}

} // namespace bfv_core
