#pragma once
// cache_bridge.h — Bridge between nshedb_gpu (Phantom BFV) and GeminiHE HECache.
//
// Contains two components:
//
//   1. BfvRotationKeyStream
//      A BFV-compatible rotation wrapper with the same public API as GeminiHE's
//      hecache::RotationKeyStream:
//          rotate_inplace(ct, step)
//          apply_galois_inplace_streaming(ct, galois_elt)
//      Calls Phantom BFV free functions (rotate_inplace / apply_galois_inplace)
//      directly, bypassing any CKKS-specific machinery.
//
//      WHY NOT RotationKeyStream?
//      hecache::RotationKeyStream (rotation_key_stream.h) has hard CKKS-specific
//      dependencies:
//        • evaluate.cuh  — KswMeta, keyswitch_get_meta, keyswitch_inplace  (CKKS GPU kernel)
//        • hecache/cpu_ksw_all.h — CpuKswTables, cpu_modup_alpha1_ckks   (CKKS CPU path)
//      These cannot be instantiated for Phantom BFV ciphertexts, so
//      RotationKeyStream is unusable as-is.  BfvRotationKeyStream is the
//      correct substitute for BFV rotation in COUNT_GPU / SUM_GPU.
//
//   2. serialize_galois_keys_for_stream()
//      Serializes a monolithic PhantomGaloisKey (as generated by
//      sk.create_galois_keys(ctx)) into the per-element directory format
//      expected by hecache::HECache::scan_keys() and preload_keys_to_cpu():
//
//          {cache_dir}/galois_mapping.txt
//          {cache_dir}/galois_index_{i}.bin    (one per galois element)
//
//      This enables a future BFV-capable RotationKeyStream (or direct HECache
//      key management) to load individual rotation keys on demand.
//
//      ── Phantom API note ────────────────────────────────────────────────────
//      Per-element key extraction uses ctx.key_galois_tool_->galois_elts() for
//      the element list, and PhantomGaloisKey::get_key(galois_elt) for each
//      key object.  If your Phantom build exposes a different method name for
//      per-element galois key access, replace the call site marked
//          // PHANTOM_API: adapt method name here
//      accordingly.  The surrounding directory and mapping-file logic is
//      API-agnostic and does not need to change.

#include <phantom.h>
#include <string>
#include <fstream>
#include <stdexcept>
#include <vector>
#include <cstdint>
#include <cstdlib>   // std::system (mkdir -p)

namespace nshedb_gpu {
namespace utils {

// ============================================================================
// BfvRotationKeyStream
//
// Drop-in replacement for hecache::RotationKeyStream in BFV contexts.
//
// The PhantomGaloisKey and PhantomContext passed at construction must both
// outlive this object.
// ============================================================================

class BfvRotationKeyStream {
public:
    // ctx and gk must outlive this wrapper.
    BfvRotationKeyStream(const PhantomContext&   ctx,
                         const PhantomGaloisKey& gk)
        : ctx_(ctx), gk_(gk) {}

    // Row-rotation by `step` slots.
    // Equivalent to hecache::RotationKeyStream::rotate_inplace(ct, step).
    void rotate_inplace(PhantomCiphertext& ct, int step) {
        phantom::rotate_inplace(ctx_, ct, step, gk_);
    }

    // Apply arbitrary galois automorphism (element elt).
    // For column swap: elt = 2*N - 1  (where N = poly_modulus_degree).
    // Equivalent to hecache::RotationKeyStream::apply_galois_inplace_streaming.
    void apply_galois_inplace_streaming(PhantomCiphertext& ct,
                                        uint32_t           galois_elt) {
        phantom::apply_galois_inplace(ctx_, ct, galois_elt, gk_);
    }

    // Accessors — mirror RotationKeyStream convention.
    const PhantomContext&   context()     const { return ctx_; }
    const PhantomGaloisKey& galois_key()  const { return gk_;  }

private:
    const PhantomContext&   ctx_;
    const PhantomGaloisKey& gk_;
};

// ============================================================================
// serialize_galois_keys_for_stream
//
// Writes the per-element key directory used by hecache::HECache::scan_keys()
// and preload_keys_to_cpu().
//
// Output layout:
//   {cache_dir}/galois_mapping.txt          — "index  galois_elt" per line
//   {cache_dir}/galois_index_{i}.bin        — binary-serialised per-element key
//
// Returns: cache_dir (for chaining).
//
// Throws std::runtime_error on I/O failure or missing galois tool.
// ============================================================================

inline std::string serialize_galois_keys_for_stream(
    const PhantomContext&   ctx,
    const PhantomGaloisKey& gk,
    const std::string&       cache_dir)
{
    // ── 1. Create output directory ───────────────────────────────────────────
    {
        // Use POSIX mkdir -p via system().  Acceptable for a one-time setup call.
        std::string cmd = "mkdir -p \"" + cache_dir + "\"";
        if (std::system(cmd.c_str()) != 0)
            throw std::runtime_error(
                "serialize_galois_keys_for_stream: cannot create directory: " +
                cache_dir);
    }

    // ── 2. Obtain ordered list of galois elements from context ───────────────
    // key_galois_tool_ is a public member of PhantomContext, populated by
    // RotationKeyStream::preload_all_cpu_evks() (or explicitly by the caller).
    // For standalone use, create the tool before calling this function:
    //
    //   auto& stream = phantom::util::global_variables::default_stream->get_stream();
    //   size_t logN = …;  // log2(poly_modulus_degree)
    //   std::vector<uint32_t> elts = …;  // your required galois elements
    //   ctx.key_galois_tool_ = std::make_unique<PhantomGaloisTool>(elts, logN, stream, false);
    //
    if (!ctx.key_galois_tool_)
        throw std::runtime_error(
            "serialize_galois_keys_for_stream: "
            "ctx.key_galois_tool_ is null.  "
            "Populate it with a PhantomGaloisTool before calling this function.");

    const std::vector<uint32_t>& galois_elts =
        ctx.key_galois_tool_->galois_elts();

    // ── 3. Write galois_mapping.txt ──────────────────────────────────────────
    {
        std::string map_path = cache_dir + "/galois_mapping.txt";
        std::ofstream map_f(map_path);
        if (!map_f)
            throw std::runtime_error(
                "serialize_galois_keys_for_stream: cannot write " + map_path);

        map_f << "# index  galois_element\n";
        for (size_t i = 0; i < galois_elts.size(); ++i)
            map_f << i << "  " << galois_elts[i] << "\n";
    }

    // ── 4. Serialize each per-element key to galois_index_{i}.bin ───────────
    //
    // We need to extract the key-switching key for each galois element from
    // the monolithic PhantomGaloisKey and serialise it as a PhantomRelinKey.
    //
    // Phantom derives from SEAL: each galois element's sub-key is stored as a
    // separate key-switch key (PhantomRelinKey in Phantom terminology).
    //
    // PHANTOM_API: adapt method name here ─────────────────────────────────────
    // If PhantomGaloisKey exposes a different accessor for per-element keys
    // (e.g. get_key_for_elt / operator[] / etc.), replace .get_key(elt) below.
    // The expected signature is:
    //     const PhantomRelinKey& PhantomGaloisKey::get_key(uint32_t galois_elt) const
    // ─────────────────────────────────────────────────────────────────────────
    for (size_t i = 0; i < galois_elts.size(); ++i) {
        uint32_t elt = galois_elts[i];
        std::string path = cache_dir + "/galois_index_" + std::to_string(i) + ".bin";
        std::ofstream out(path, std::ios::binary);
        if (!out)
            throw std::runtime_error(
                "serialize_galois_keys_for_stream: cannot write " + path);

        // PHANTOM_API: adapt method name here.
        // This call extracts the per-element relin key and serialises it.
        const PhantomRelinKey& elem_key = gk.get_key(elt);
        elem_key.save(out);
    }

    return cache_dir;
}

} // namespace utils
} // namespace nshedb_gpu
